version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        port: ${PORT}
    restart: always
    ports:
      - '50140:${PORT}'
    env_file:
      - .env
    environment:
      WAIT_HOSTS: database:27017
  database:
    image: mongo:4.0
    env_file:
      - .env
    volumes:
      - '.${MONGO_DATA_DIR}:${MONGO_DATA_DIR}'
    expose:
      - 27017
    command: 'mongod --smallfiles --logpath=${MONGO_LOG_FILE}'
